### ISSUE TITLE
Execution Architecture

### ISSUE THREAD

**Issue by andeek** [gammarama/intRo#3] opened 2014-09-30 14:37 UTC
Do we want to have everything run on load? Or on click of individual modules. I think the latter.

**Comment by erichare** [comment] 2015-09-20 14:12
I looked into this one some more, and I think its going to be difficult...

The stackoverflow posts shows how you can delay execution until a tab is clicked. That's exactly what we want. The problem is that it depends on being able to check the value of a reactive variable - With ggvis, the expressions are not reactive (the data itself is a reactive expression), so the ggvis plots will try to display on startup. Theoretically we could do it for the other modules, but I think that could get very messy if some are loading on startup and some are delayed.

I think in the meantime we can go ahead and close this. It could definitely speed the initial startup if we find a solution, but it would also slow the loading of each tab and probably involve a lot of code refactoring.

**Closed by erichare** 2015-09-20 14:12 UTC
Labels: bug, enhancement
